### ISSUE TITLE
Product name

### ISSUE THREAD

**Issue by rylm** [colincowie/SupremeAutoPurchase#2]
How do you find the correct product by product name?

A good idea here would be some keywords parser.

**Comment by colincowie** [comment]
I use BeautifulSoup to parse through the html to pull all the products online and I use my `checkproduct(link,product,color)` to check if the product is online.

**Comment by Hezion** [comment]
What exactly do you mean? Do you want to be able to add a list of keywords that should be monitored? 
Right now you can work with substrings, so if you look for "Fishtail" you will find the actual product "Wool Fishtail Parka".

**Comment by rylm** [comment]
Could you please explain this piece of code to me?

for a in div.find_all(['h1','p']):
            if(a.name=='h1'):
                product = a.text
            elif(a.name=='p'):
                color = a.text

I'm not clear with how you select the color AND the product. From the start they are empty strings.

**Comment by colincowie** [comment]
@rylm With the way suprume's website is set up unfortunately they don't have it indexed as shop/all/whitesocks, instead the have a random string. To find the desired products link we navigate to the items sub-page such as /shop/all/jackets or /shop/all/accessories. Supreme sites has every item in it's own article that is formatted like [this](http://i.imgur.com/YByLahW.png) so we find the <a> tag that contains the product and then the <h1> tag that contains the color. Once we have the product and the color, we check it with the function checkproduct(link,product,color) to see if it matches what the user selected in the config.ini
