### ISSUE TITLE
Question about Bot

### ISSUE THREAD

**Issue by PriorKibbles** [colincowie/SupremeAutoPurchase#3]
I was wondering if I am doing it right. That yellow text keeps popping up and I was wondering do I need to fix that? Can you verify? 
Also, I keep getting this error: http://imgur.com/a/LoYZw
How can I fix this and one last thing: I only input my information into the buy.py right? Not the config.cfg? Or should I do both?

**Comment by Hezion** [comment]
You can safely ignore the yellow warnings. 

The error you are gettings looks like the text you put in that line seems to have a mixed encoding.
